# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
dist: trusty
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
cache:
  directories:
  - test/kernels
# uncomment the following lines to override the default test script
# script:
#  - echo $TRAVIS_JULIA_VERSION
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("SPICE"); Pkg.test("SPICE"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SPICE")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SPICE")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("SPICE")); include(joinpath("docs", "make.jl"))'

